

export interface VariableOption {
    id: string;
    name: string;
    value: number;
    abbreviation: string;
}

export interface Variable {
  id?: string; // Optional because it's generated by Firestore
  name: string;
  type: 'boolean' | 'enumeration' | 'numeric' | 'text';
  possibleValues: VariableOption[];
  description?: string; 
  createdAt?: any;
  usedIn?: { id: string, name: string }[];
}

export interface AnalysisResult {
  naturalLanguageDecisionTree: string;
  jsonDecisionTree: string;
  questionsScript: string;
}

export interface MediaItem {
    name: string;
    type: 'image' | 'video';
    url: string;
    originalFilename?: string;
}

export interface LinkItem {
  name: string;
  url: string;
}

export interface TriggerItem {
    name: string;
    path: string;
}

export interface DecisionLeaf {
  id?: string;
  decision: string;
  media?: MediaItem[];
  links?: LinkItem[];
  triggers?: TriggerItem[];
}

export type DecisionOptionChild = DecisionNode | DecisionLeaf | string | { ref: string, id?: string } | { subTreeRef: string, id?: string };


export interface DecisionNode {
  id?: string;
  question?: string;
  variableId?: string; // ID for standardized variable
  options?: {
    [key: string]: DecisionOptionChild;
  };
  possibleValues?: VariableOption[]; // To store options for standard vars
  decision?: string; // Kept for backward compatibility or simple cases
  media?: MediaItem[];
  links?: LinkItem[];
  triggers?: TriggerItem[];
  ref?: string;
  subTreeRef?: string;
}

export interface StoredTree extends AnalysisResult {
    id: string;
    name: string;
    description: string;
    createdAt?: any; 
}

export type DiagnoseProblemOutput = {
    question: string;
    options?: string[];
    isFinalDecision: boolean;
    treeName?: string;
};

export type ConsolidationProposal = {
    type: 'add';
    treeVariable: Variable;
} | {
    type: 'merge';
    treeVariable: Variable;
    dbVariable: Variable;
};
