

export interface VariableOption {
  id: string;
  name: string;
  value: number;
  abbreviation: string;
}

export interface Variable {
  id?: string; // Optional because it's generated by Firestore
  name: string;
  type: 'boolean' | 'enumeration' | 'numeric' | 'text';
  possibleValues: VariableOption[];
  description?: string;
  createdAt?: any;
  usedIn?: { id: string, name: string }[];
}

export interface AnalysisResult {
  naturalLanguageDecisionTree: string;
  jsonDecisionTree: string;
  questionsScript: string;
}

export interface MediaItem {
  name: string;
  type: 'image' | 'video';
  url: string;
  originalFilename?: string;
}

export interface LinkItem {
  name: string;
  url: string;
}

export interface TriggerItem {
  name: string;
  path: string;
}

export interface EmailActionConfig {
  enabled: boolean;
  connectorId: string; // SMTP connector ID

  // Recipients
  to: string;         // Comma-separated or dynamic from variables
  cc?: string;
  bcc?: string;

  // Content
  subject: string;
  body: string;       // HTML content

  // Attachments configuration - arrays of selected table names
  attachments: {
    tablesInBody: string[];          // Names of tables to show in email body
    tablesAsExcel: string[];         // Names of tables to attach as Excel
    pythonOutputsInBody: string[];   // Names of Python outputs in body
    pythonOutputsAsAttachment: string[]; // Names of Python outputs as attachments
    mediaAsAttachment: string[];     // Filenames or URLs of media to attach
  };
}

export type WidgetType = 'table' | 'bar-chart' | 'line-chart' | 'area-chart' | 'pie-chart' | 'kpi-card';

export interface WidgetConfig {
  type: WidgetType;
  title?: string;
  description?: string;
  isPublished?: boolean; // Flag to publish widget to dashboard library
  xAxisKey?: string;
  xAxisTitle?: string;
  yAxisTitle?: string;
  xAxisDy?: number;
  yAxisDx?: number;
  lineStyle?: 'solid' | 'dashed' | 'dotted';
  legendPosition?: 'top' | 'bottom' | 'left' | 'right';
  dataKeys?: string[];
  colors?: string[]; // Hex colors
  kpiValueKey?: string;
  kpiLabel?: string;
  data?: any[]; // Sealed data for persistence
  // Data Source Config
  dataSourceType?: 'current-sql' | 'current-python' | 'parent-table';
  dataSourceId?: string; // Table name for parent-table, or 'sql'/'python' for current
}

export interface DecisionLeaf {
  id?: string;
  decision: string;
  media?: MediaItem[];
  links?: LinkItem[];
  triggers?: TriggerItem[];
  sqlQuery?: string;
  sqlConnectorId?: string;
  sqlResultName?: string;
  pythonCode?: string;
  pythonOutputType?: 'table' | 'variable' | 'chart';
  pythonResultName?: string;
  pythonConnectorId?: string;
  pythonSelectedPipelines?: string[];
  sqlSelectedPipelines?: string[];
  emailAction?: EmailActionConfig;
  widgetConfig?: WidgetConfig;
  // SQL Export Config
  sqlExportTargetTableName?: string;
  sqlExportTargetConnectorId?: string;
  sqlExportSourceTables?: string[];
  sqlExportStatus?: 'idle' | 'running' | 'success' | 'error';
  sqlExportLastRun?: number;
}

export type SingleDecisionOptionChild = DecisionNode | DecisionLeaf | string | { ref: string, id?: string } | { subTreeRef: string, id?: string };

export type DecisionOptionChild = SingleDecisionOptionChild | SingleDecisionOptionChild[];


export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: number;
  // Optional preview data to display charts/tables inline
  preview?: {
    type: 'table' | 'chart' | 'variable';
    data?: any[];
    columns?: any[];
    chartHtml?: string;
    chartBase64?: string;
    variables?: any;
    debugLogs?: string[];
  };
}

export interface DecisionNode {
  id?: string;
  question?: string;
  variableId?: string; // ID for standardized variable
  options?: {
    [key: string]: DecisionOptionChild;
  };
  possibleValues?: VariableOption[]; // To store options for standard vars
  decision?: string; // Kept for backward compatibility or simple cases
  media?: MediaItem[];
  links?: LinkItem[];
  triggers?: TriggerItem[];
  sqlQuery?: string;
  sqlConnectorId?: string;
  sqlResultName?: string;
  sqlSelectedPipelines?: string[];
  sqlChatHistory?: ChatMessage[];
  ref?: string;
  subTreeRef?: string;
  pythonCode?: string;
  pythonOutputType?: 'table' | 'variable' | 'chart';
  pythonResultName?: string;
  pythonConnectorId?: string;
  pythonSelectedPipelines?: string[];
  pythonChatHistory?: ChatMessage[];
  emailAction?: EmailActionConfig;
  widgetConfig?: WidgetConfig;
  // SQL Export Config
  sqlExportTargetTableName?: string;
  sqlExportTargetConnectorId?: string;
  sqlExportSourceTables?: string[];
  sqlExportStatus?: 'idle' | 'running' | 'success' | 'error';
  sqlExportLastRun?: number;
}

export interface StoredTree extends AnalysisResult {
  id: string;
  name: string;
  description: string;
  createdAt?: any;
  type?: string;
  companyId?: string | null;
}

export interface DiagnosticNode {
  text: string;
  media?: MediaItem[];
  links?: LinkItem[];
  triggers?: TriggerItem[];
  id?: string;
}

export type DiagnoseProblemOutput = {
  question: string;
  options?: string[];
  isFinalDecision: boolean;
  treeName?: string;
  media?: MediaItem[];
  links?: LinkItem[];
  triggers?: TriggerItem[];
  nodeIds?: string[];
  nodes?: DiagnosticNode[];
};

export type ConsolidationProposal = {
  type: 'add';
  treeVariable: Variable;
} | {
  type: 'merge';
  treeVariable: Variable;
  dbVariable: Variable;
};

// ============================================
// AI AGENT TYPES
// ============================================

export interface AgentChatMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: number;
  scriptSnapshot?: string;
}

export interface AgentConversation {
  id: string;
  nodeId: string;
  agentType: 'sql' | 'python';
  script: string;
  tableSchema?: Record<string, string[]>;
  inputTables?: Record<string, any[]>;
  messages: AgentChatMessage[];
  companyId?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface AgentRequest {
  nodeId: string;
  agentType: 'sql' | 'python';
  userMessage: string;
  script: string;
  tableSchema?: Record<string, string[]>;
  inputTables?: Record<string, any[]>;
}

export interface AgentResponse {
  success: boolean;
  message: string;
  updatedScript?: string;
  needsClarification: boolean;
  clarificationQuestions?: string[];
  conversationId?: string;
}
