import type { UnifiedStylePreset } from '@/lib/unified-style-types';

export const BUILTIN_PRESETS: UnifiedStylePreset[] = [
    {
        id: 'builtin_default',
        label: 'Default',
        description: 'Stile predefinito con colori neutri e toni indaco.',
        category: 'corporate',
        html: {},
        plotly: {},
        ui: {},
        createdAt: '2024-01-01T00:00:00.000Z',
        isBuiltIn: true,
    },
    {
        id: 'builtin_minimal',
        label: 'Minimal',
        description: 'Stile minimalista con sfondo bianco e bordi sottili.',
        category: 'minimal',
        html: {
            body_bg_color: '#ffffff',
            body_text_color: '#111827',
            header_bg_color: '#f9fafb',
            header_text_color: '#374151',
            border_color: '#e5e7eb',
            stripe_color: '#f9fafb',
        },
        plotly: {},
        ui: {
            btn_bg_color: '#111827',
            btn_text_color: '#ffffff',
            btn_hover_bg_color: '#374151',
            btn_border_radius: 4,
            btn_shadow: 'none',
            card_border_radius: 4,
            card_shadow: 'none',
        },
        createdAt: '2024-01-01T00:00:00.000Z',
        isBuiltIn: true,
    },
    {
        id: 'builtin_corporate',
        label: 'Corporate Blue',
        description: 'Stile aziendale professionale con tonalità blu.',
        category: 'corporate',
        html: {
            body_bg_color: '#f0f4f8',
            body_text_color: '#1a202c',
            header_bg_color: '#1e40af',
            header_text_color: '#ffffff',
            border_color: '#bfdbfe',
            stripe_color: '#eff6ff',
        },
        plotly: {
            colorway: ['#1e40af', '#3b82f6', '#60a5fa', '#93c5fd', '#bfdbfe'],
        },
        ui: {
            btn_bg_color: '#1e40af',
            btn_text_color: '#ffffff',
            btn_hover_bg_color: '#1d4ed8',
            btn_border_radius: 6,
            badge_bg_color: '#dbeafe',
            badge_text_color: '#1e40af',
        },
        createdAt: '2024-01-01T00:00:00.000Z',
        isBuiltIn: true,
    },
    {
        id: 'builtin_dark',
        label: 'Dark',
        description: 'Tema scuro elegante per ambienti a bassa luminosità.',
        category: 'dark',
        html: {
            body_bg_color: '#0f172a',
            body_text_color: '#e2e8f0',
            header_bg_color: '#1e293b',
            header_text_color: '#94a3b8',
            border_color: '#334155',
            stripe_color: '#1e293b',
        },
        plotly: {
            paper_bgcolor: '#0f172a',
            plot_bgcolor: '#1e293b',
            font_color: '#94a3b8',
            colorway: ['#818cf8', '#34d399', '#f59e0b', '#f87171', '#60a5fa'],
        },
        ui: {
            btn_bg_color: '#6366f1',
            btn_text_color: '#ffffff',
            btn_hover_bg_color: '#4f46e5',
            btn_border_radius: 6,
            input_bg_color: '#1e293b',
            input_text_color: '#e2e8f0',
            input_border_color: '#334155',
            card_bg_color: '#1e293b',
            card_border_color: '#334155',
        },
        createdAt: '2024-01-01T00:00:00.000Z',
        isBuiltIn: true,
    },
    {
        id: 'builtin_finance',
        label: 'Finance',
        description: 'Stile per report finanziari con enfasi su dati numerici.',
        category: 'finance',
        html: {
            body_bg_color: '#ffffff',
            body_text_color: '#111827',
            header_bg_color: '#064e3b',
            header_text_color: '#ecfdf5',
            border_color: '#d1fae5',
            stripe_color: '#f0fdf4',
            positive_color: '#059669',
            negative_color: '#dc2626',
        },
        plotly: {
            colorway: ['#059669', '#1d4ed8', '#d97706', '#dc2626', '#7c3aed'],
        },
        ui: {
            btn_bg_color: '#059669',
            btn_text_color: '#ffffff',
            btn_hover_bg_color: '#047857',
            badge_bg_color: '#d1fae5',
            badge_text_color: '#065f46',
        },
        createdAt: '2024-01-01T00:00:00.000Z',
        isBuiltIn: true,
    },
];
